<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputuserPassword</name>
   <tag></tag>
   <elementGuidId>97cd1e74-42fb-4c96-90d4-4ad2d48493e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab7eb2c0-34f4-4b34-89aa-4b2530a22d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>26c55381-9eb8-4495-b59f-9fccd14534cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>userPassword</value>
      <webElementGuid>f943039f-b993-4b1f-97c2-3070da8f918f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userPassword</value>
      <webElementGuid>eea7c2fc-e6ce-4880-8dd4-f6a6a288fe8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>enter your passsword</value>
      <webElementGuid>834b32f1-ea1c-4394-a2cc-f1253814072b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>9f4c4efb-3155-4e44-bf73-7757eb92e302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userPassword&quot;)</value>
      <webElementGuid>17239240-5b35-4f0e-8349-62f5e7f78534</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userPassword']</value>
      <webElementGuid>2ab28bc9-8b4a-4f88-a4d6-9bd9c38a25bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>9a2744e1-42e1-426d-a559-abc98b2d050f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'userPassword' and @placeholder = 'enter your passsword']</value>
      <webElementGuid>1a20bd71-a1a1-437e-8db9-82cb33f27ad4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
