<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>orangeHRM_suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>9336c916-44fd-4dcc-81d7-268b2fafc9a1</testSuiteGuid>
   <testCaseLink>
      <guid>65dd5d3c-e1f7-4b32-b349-902b7a7ab2f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/OrangeHRM</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>5dcafdbf-b1c0-43a3-affc-42143ee8a06e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/OrangeHRMData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>5dcafdbf-b1c0-43a3-affc-42143ee8a06e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USERNAME</value>
         <variableId>9d4b4426-8c9f-4a6c-8582-5e2584e714a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>5dcafdbf-b1c0-43a3-affc-42143ee8a06e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PASSWORD</value>
         <variableId>52eae131-b7fb-4c1d-8927-248b4eae19c3</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
